#!/bin/bash
### https://arjunsreedharan.org/post/82710718100/kernel-101-lets-write-a-kernel ###
nasm -f elf32 kernel.asm -o kasm.o
nasm -f elf32 gdt.asm -o gdt.o
gcc -m32 -c kernel.c -o kc.o
ld -m elf_i386 -T link.ld -o kernel kasm.o kc.o gdt.o
