# export TURBOFISH_ROOT in you shell configuration file to execute this Makefile independently
include $(TURBOFISH_ROOT)/boilerplates.mk

.PHONY: all clean fclean re

all:

clean:

fclean:

re: fclean all
